version: "3.8"
services:
  web:
    build:
      context: ./EptaCombine
    ports:
      - "5000:80"
    depends_on:
      - fileconverter

  fileconverter:
    build:
      context: ./FileConverter
    ports:
      - "5001:80"
  
  latexcompiler:
    build:
      context: ./LatexCompiler
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LatexCompilerDatabase;Username=eptauser;Password=q$bYhFF6
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: LatexCompilerDatabase
      POSTGRES_USER: eptauser
      POSTGRES_PASSWORD: q$bYhFF6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: