version: "3.8"
services:
  web:
    build:
      context: ./EptaCombine
    ports:
      - "5000:80"
    depends_on:
      - fileconverter

  fileconverter:
    build:
      context: ./FileConverter
    ports:
      - "5001:80"
  
  latexcompiler:
    build:
      context: ./LatexCompiler
    ports:
      - "5002:80"