services:
  web:
    build:
      context: .
      dockerfile: EptaCombine/Dockerfile
    ports:
      - "5100:8080"
    depends_on:
      - fileconverter
      - db
    volumes:
      - aspnet-data:/usr/share/aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_DATA_PROTECTION__KEY_RING_PATH=/usr/share/aspnet/DataProtection-Keys
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EptaCombineDatabase;Username=eptauser;Password=qWbYhFF6

  fileconverter:
    build:
      context: .
      dockerfile: FileConverter/Dockerfile
    ports:
      - "5101:8080"
  
  latexcompiler:
    build:
      context: .
      dockerfile: LatexCompiler/Dockerfile
    ports:
      - "5102:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=LatexCompilerDatabase;Username=eptauser;Password=qWbYhFF6
    depends_on:
      - db
    volumes:
      - latexcompiler_data:/var/lib/latexcompiler
  
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: LatexCompilerDatabase
      POSTGRES_USER: eptauser
      POSTGRES_PASSWORD: qWbYhFF6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  aspnet-data:
  latexcompiler_data:
